### ISSUE TITLE
Extend `extinct_species()`

### ISSUE THREAD

**Issue by ismael-lajaaiti** [BecksLab/EcologicalNetworksDynamics.jl#110]
## TODO 

- [ ] rename get_extinct_species to get_extinction_events as the function return events (which species has gone extinct and when) and not only extinct species list
- [ ] create an `get_extinct_species(extinction_events, t)` that given the dictionary of `extinction_events` return the list of extinct species at the time step `t`
- [ ] create `get_alive_species`, the sister of `get_extinction_species` that return alive species instead of dead species, as in some cases in can be more convenient in this way
